version: '3.7'

services:
  app:
    container_name: app
    image: app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - app_db
      - app_redis

  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:15.4-alpine3.18
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app_redis:
    image: redis:7.2.2-alpine3.18
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - 6379:6379
    networks:
      - backend

volumes:
  app_pg_data:
    driver: "local"

networks:
  backend:
    driver: 'bridge'
